# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(303, 216)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inp_grade = QtWidgets.QLineEdit(Dialog)
        self.inp_grade.setObjectName("inp_grade")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_grade)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.inp_roast = QtWidgets.QLineEdit(Dialog)
        self.inp_roast.setObjectName("inp_roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inp_roast)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.inp_ground_or_beans = QtWidgets.QLineEdit(Dialog)
        self.inp_ground_or_beans.setObjectName("inp_ground_or_beans")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_ground_or_beans)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.inp_description = QtWidgets.QLineEdit(Dialog)
        self.inp_description.setObjectName("inp_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inp_description)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.inp_price = QtWidgets.QLineEdit(Dialog)
        self.inp_price.setObjectName("inp_price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inp_price)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.inp_volume = QtWidgets.QLineEdit(Dialog)
        self.inp_volume.setObjectName("inp_volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inp_volume)
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setObjectName("btn_save")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_save)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Кофе"))
        self.label.setText(_translate("Dialog", "Сорт"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Молотый / В зернах"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label_6.setText(_translate("Dialog", "Объем упаковки"))
        self.btn_save.setText(_translate("Dialog", "Сохранить"))
